# public/admin/config.yml

backend:
  name: git-gateway
  repo: samuelmaker/daniel-aihie-netlify
  branch: main

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

# Here we define content structure
collections:
  - label: "Edits"
    name: "edits"
    folder: "src/content/edits"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - label: "Creative"
    name: "creative"
    folder: "src/content/creative"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
